pub(crate) const INSULTS: &[&str] = &[
    "Were you born yesterday?",
    "This is embarrassing, have you ever considered another profession?",
    "Do you know how to use the tab key?",
    "Closing your parenthesis and braces usually helps your code run...",
    "Did you actually make a change to this code or are just rerunning it because you think I made a mistake?",
    "Bruh, wtf this\nSincerely,\nYour Computer",
    "Next time, try writing code that will work",
    "Please return to Monke",
    "Randomly generated code would run better",
    "Did you really think this through?",
    "I would tell you why your code dosnt work here if i could make any sense out of it myself",
    "I could do this better recursively calling main()",
    "\"Hello World!\"\n\nLMAO jk it didnt work",
    "I suggest Stack Overflow",
    "There are so many errors here I dont even know where to start... ",
    "Who hurt you?",
    "Go touch some grass",
	"I bet your mom called you special, didn't she?",
];
